# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: vdubovets
  tag: v1.0.5-65c325e
  arch: arm64

secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
